### ISSUE TITLE
Classfiers have no method predict_proba

### ISSUE THREAD

**Issue by zshgostop** [wmkouw/libTLDA#14]
The libtlda is installed by pip. The version of libtlda is 0.1.5. When I use SubspaceAlignedClassifier, it throws an“ AttributeError: 'SubspaceAlignedClassifier' object has no attribute 'predict_proba'”.
  Is mehtod "predict_proba" removed from these classfiers?

**Comment by wmkouw** [comment]
Yes, it wasn't added. Issue #11 lists methods by scikit that I still haven't implemented.

However, I switched positions and don't have time for this repo anymore. I don't think I will have time to add this feature anytime soon.
